% Original code written by Blake Hourigan for Samuelsen Lab, Univeristy of Louisville----
% V2 code edited/written by Timothy Vladimir Dong for Samuelsen Lab, Univeristy of Louisville----

%% TESTING PROTOCOL V3 | 2 OPERANT RESPONSE TASK
% V3 Update description: This protocol is used with a center spout connected to a multi-channel manifold and a vacuum. 
% The inside of the spout only contains a single shared channel for all stimuli, with one other channel used to channel
% the vac. Stimuli are loaded from the manifold and rinsed out with water. Rinse and waste stimuli are
% cleared by the vacuum. 

% Stimulus valves should be calibrated for 10ul pulses when delivering stimuli, with an additional measurement around 
% 500ms to calibrate the longer preloading pulse (the preloading duration will be averaged across valves). 

function testing_v3_rinseSharedChannel
    
    global BpodSystem % Imports the BpodSystem object to the function workspace

    %% SET UP SESSION
    expV = ExperimentVariables(); %expV is used to access experiment constants

    % Setup for wave player
    Fs = 44100;    % Sampling rate in Hz (e.g., CD quality)
    T = .5;         % Duration in seconds
    f = 800;       % Frequency of the tone in Hz
    t = 0:1/Fs:T; % Generate the time vector
    y = sin(2*pi*f*t); % Generate the sinusoidal waveform

    BpodSystem.Status.trial = 1;
    BpodSystem.Status.consecutiveRatSkips = 0;
    BpodSystem.Status.ExitTrialLoop = false; % session end 
    BpodSystem.Status.switchStimulusFlag = false; % used to indicate when middle stimulus should switch (for alternation). 

    % Organizing what to save to data structure
    BpodSystem.Data.condition = ''; 
    BpodSystem.Data.correctTrials = nan(expV.MAXIMUM_TRIALS, 1);
    BpodSystem.Data.correctPort = zeros(expV.MAXIMUM_TRIALS, 1);
    BpodSystem.Data.centerValve = zeros(expV.MAXIMUM_TRIALS, 1);
    BpodSystem.Data.rewardLick = zeros(expV.MAXIMUM_TRIALS, 1);
    BpodSystem.Data.trialsEngaged = zeros(expV.MAXIMUM_TRIALS, 1);

    % Saving ExperimentVariables
    propNames = properties(expV); propValues = cell(size(propNames));
    for i = 1:numel(propNames); propValues{i} = expV.(propNames{i}); end
    expVarTable = cell2table(propValues,'RowNames', propNames, 'VariableNames', {'Value'}); % Convert to table
    BpodSystem.Data.experimentVariables = expVarTable; % Save table to structure

    % Generating lineup and jitter for valve openings
    [center_port_valve_lineup, reward_lick_lineup, ~] = GenerateCenterLineup();
    %BpodSystem.Data.centerValveDelay = center_delay_lineup; 

    % configure the analog in. performed in configure_analog_in.m
    A = configure_analog_in();

    % Set up wave player
    W = BpodWavePlayer(BpodSystem.ModuleUSB.WavePlayer1);
    W.SamplingRate = Fs;
    W.loadWaveform(1, y); % Loads a sound as waveform 1

    %% LOAD ProtocolSettings
    S = BpodSystem.ProtocolSettings; % Loads settings file chosen in launch manager into current workspace as a struct called 'S'
    subj = BpodSystem.GUIData.SubjectName;
    if isempty(S) || isempty(fieldnames(S)) % If running this protocol for the first time with this subject, or if settings cannot be found
        dir = ['C:\Users\Chad Samuelsen\Documents\Github\Bpod Local\Data\',subj,'\Set_exp_parameters\Session Settings\DefaultSettings.mat'];
        temp = load(dir);
        S = temp.ProtocolSettings; clear temp;
        
        BpodSystem.ProtocolSettings = S;
    end

    % UPDATE valve open times for parameter sheet
    centerValves = [expV.VALVE_SET1, expV.VALVE_SET2]; 
    S = update_valve_open_times(S, [1, centerValves, expV.RINSE_VALVE, 8], expV.STIM_VOLUME);
    
    % Save protocol settings (after updating valve timings)
    BpodSystem.ProtocolSettings = S;
    SaveProtocolSettings(BpodSystem.ProtocolSettings)
    
    BpodParameterGUI('init', S); % initialize GUI to keep track of parameters

    % GET CONDITION FOR CURRENT SUBJECT
    conditions = S.GUIMeta.CONDITION_CODE.String;
    if ~any(contains(conditions, "null")); error('Error: no condition selected for this subject. '); end
    SUBJECT_CONDITION_CODE = conditions(~contains(conditions, "null")); 
    BpodSystem.Data.condition = SUBJECT_CONDITION_CODE;
    
    %% Generate port instances
    % port_1 is the instance of the class Port1
    port_1 = LateralPort(1);
    % port_3 is the instance of the class Port3
    port_3 = LateralPort(3);
    % center_port the instance of the class center_port
    center_port = CenterPort;
    correct_port = PortHandler;
    incorrect_port = PortHandler;
    
    % save valve open times to session data
    valveID = ["Valve1"; "Valve2"; "Valve3"; "Valve4"; "Valve5"; "Valve6"; "Valve7"; "Valve8"];
    valveOpenTimes = [BpodSystem.ProtocolSettings.GUI.open_time_1; BpodSystem.ProtocolSettings.GUI.open_time_2; ...
        BpodSystem.ProtocolSettings.GUI.open_time_3; BpodSystem.ProtocolSettings.GUI.open_time_4; ...
        BpodSystem.ProtocolSettings.GUI.open_time_5; BpodSystem.ProtocolSettings.GUI.open_time_6; 
        BpodSystem.ProtocolSettings.GUI.open_time_7; BpodSystem.ProtocolSettings.GUI.open_time_8];
    BpodSystem.Data.valveOpenTimes = table(valveID,valveOpenTimes); % This time is in ms
    
    % Get valve times for rinse and loading, and make sure the values allow for full ITI 
    valveLoadingTime = ceil(mean(GetValveTimes(expV.LOAD_VOLUME, centerValves))*100)/100; 
    valveRinseTime = GetValveTimes(expV.RINSE_VOLUME, expV.RINSE_VALVE); 
    if (expV.ITI_TIME - expV.ITI_ENDTIME) < (valveLoadingTime + valveRinseTime + 2)
        error('Error: calibration values for rinse and preloading are incompatible with this protocol. '); 
    end
    
    % totalValveWindow = ceil(mean(valveOpenTimes)/100)*100; % round up to nearest 100 ms to set stim window
    % fullStimWindow = (totalValveWindow/1000) + expV.STIMULUS_WINDOW; % convert totalValve window to seconds
    % BpodSystem.Data.fullStimulusWindow = fullStimWindow; 

    % Print to command window the start of the Session
    disp(['Subject Name: ' subj]);
    disp(['Condition: ' char(SUBJECT_CONDITION_CODE)]);
    fprintf('Date and time: %s\n',datetime("now"))
    fprintf(['Valve Durations (' num2str(expV.STIM_VOLUME), 'ul): ']); 
    for iValves=1:length(valveID); fprintf('%s=%.1fms. ',num2str(iValves),valveOpenTimes(iValves)); end
    fprintf(['\nLoad: ' num2str(expV.LOAD_VOLUME), 'ul, ', num2str(valveLoadingTime), 'ms. '])
    fprintf(['Rinse: ' num2str(expV.RINSE_VOLUME), 'ul, ', num2str(valveRinseTime), 'ms. '])
    fprintf('\n')
    
    clear elapsedTime; 
    elapsedTime; % First call of timer function to track session length

    %% MAIN TRIAL LOOP
    % do MAXIMUM_TRIALS as defined in ExperimentVariables file if 60 minutes has not elapsed.
    for trial = 1:expV.MAXIMUM_TRIALS
        
        S = BpodParameterGUI('sync', S); % Sync parameters with BpodParameterGUI plugin
        
        %% Get parameters for the current trial and save to variables
        BpodSystem.Status.trial  = trial;
        fprintf('Trial %d: ', trial)

        % Get center valve and number of dry licks for this trial
        center_stimulus_valve = center_port_valve_lineup(trial); 
        num_dryLicks = reward_lick_lineup(trial)-1;
        %center_valveDelay = center_delay_lineup(trial);

        % Set center valve and correct port -> WHERE CORRECT CHOICE IS DEFINED
        center_port = center_port.setValve(1, center_stimulus_valve);
        correct_port = correct_port.setCorrect(port_1, port_3, center_stimulus_valve, expV.VALVE_SET1, expV.VALVE_SET2, ...
            SUBJECT_CONDITION_CODE);
        incorrect_port = incorrect_port.setIncorrect(port_1, port_3, center_stimulus_valve, expV.VALVE_SET1, expV.VALVE_SET2, ...
            SUBJECT_CONDITION_CODE);

        % new trial *block*, reset consecutiveRatSkips
        if (mod(trial, (expV.TRIALS_PER_BLOCK + 1)) == 0)
            BpodSystem.Status.consecutiveRatSkips = 0;
        end
        % evaluate if minimum trial number is reached, and if 10 consecutive traials have been skipped
        % if (expV.MINIMUM_TRIALS) 
        %     if(BpodSystem.Status.consecutiveRatSkips >= expV.SKIPPED_TRIALS_THRESHOLD)
        %         stop_experiment(A, W);
        %         return
        %     end
        % end

        fprintf('Center=valve%d. DryLicks=%d. ', center_stimulus_valve, num_dryLicks);
        fprintf('Correct=port%d. ', correct_port.port); %fprintf('Incorrect=port%d. ', incorrect_port.port);

        %% Assemble the State Machine for this Trial
        sma = NewStateMachine();

        % set global timers for the maximum duration of the experiment and the maximum sample time of 2 seconds.
        sma = SetGlobalTimer(sma, 'TimerID', expV.ITI_TIMER_ID, 'Duration', (expV.ITI_TIME - expV.ITI_ENDTIME) );
        sma = SetGlobalTimer(sma, 'TimerID', expV.LICK_WINDOW_TIMER_ID, 'Duration', expV.LICK_WINDOW); % 2 seconds to get all dry licks
        %sma = SetGlobalTimer(sma, 'TimerID', expV.STIM_WINDOW_TIMER_ID, 'Duration', fullStimWindow); % Max time after valve opens before door goes up

        % set global counters for each of the possible input ports (AnalogIn1 ports 1-4). 
        % Arguments: (sma, CounterNumber, TargetEvent, Threshold)
        sma = SetGlobalCounter(sma, center_port.LEFT_COUNTER_ID, center_port.LEFT_LICK_INPUT, num_dryLicks); 
        %sma = SetGlobalCounter(sma, center_port.RIGHT_COUNTER_ID, center_port.RIGHT_LICK_INPUT, num_dryLicks);
        sma = SetGlobalCounter(sma, port_1.COUNTER_ID, port_1.LICK_INPUT, 3);
        sma = SetGlobalCounter(sma, port_3.COUNTER_ID, port_3.LICK_INPUT, 3);

        BpodSystem.Data.centerValve(trial) = center_port.left_valve;
        BpodSystem.Data.correctPort(trial) = correct_port.port;
        BpodSystem.Data.rewardLick(trial) = num_dryLicks+1;

        %% Adding States

        %%%% MAIN ITI WITH RINSE AND STIMULUS LOADING %%%%%
        sma = AddState(sma, 'Name', 'trialStart', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_rinseAndVacStart'},...
            'OutputActions', {port_1.DOOR, expV.UP, center_port.DOOR, expV.UP, port_3.DOOR, expV.UP, ...
            'ValveModule1', ['B' 00000000], expV.VAC_VALVE, 0});
        sma = AddState(sma, 'Name', 'ITI_rinseAndVacStart', ...
            'Timer', valveRinseTime,...
            'StateChangeConditions', {'Tup', 'ITI_endRinse'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.VAC_VALVE, 1, 'ValveModule1', ['O' expV.RINSE_VALVE], ...
            'GlobalTimerTrig', expV.ITI_TIMER_ID});
        sma = AddState(sma, 'Name', 'ITI_endRinse', ...
            'Timer', 0.25,...
            'StateChangeConditions', {'Tup', 'ITI_startStimLoad'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.VAC_VALVE, 1, 'ValveModule1', ['C' expV.RINSE_VALVE]});    
        sma = AddState(sma, 'Name', 'ITI_startStimLoad', ...
            'Timer', valveLoadingTime,...
            'StateChangeConditions', {'Tup', 'ITI_endStimLoad'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.VAC_VALVE, 1, 'ValveModule1', ['O' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'ITI_endStimLoad', ...
            'Timer', 1.5,...
            'StateChangeConditions', {'Tup', 'ITI_waitForRemaining', expV.itiTimeExpired, 'TTC_Center'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.VAC_VALVE, 1, 'ValveModule1', ['C' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'ITI_waitForRemaining', ...
            'Timer', 0,...
            'StateChangeConditions', {expV.itiTimeExpired, 'TTC_Center'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.VAC_VALVE, 0, 'GlobalCounterReset', center_port.LEFT_COUNTER_ID});
        
        %%%%% TRIAL START %%%%%
        sma = AddState(sma, 'Name', 'TTC_Center', ...
            'Timer', expV.TTC_CENTER_TIME,...
            'StateChangeConditions', {'Tup', 'reportSkip', center_port.LEFT_LICK_INPUT, 'waitCenterDryLicks'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'AnalogIn1', ['#' 0], 'WavePlayer1', ['P' 8 0]});
        sma = AddState(sma, 'Name', 'waitCenterDryLicks', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LEFT_COUNTER_EVENT, 'waitCenterSampleLick1', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'GlobalTimerTrig', expV.LICK_WINDOW_TIMER_ID});
        sma = AddState(sma, 'Name', 'waitCenterSampleLick1', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LEFT_LICK_INPUT, 'openCenterValve1', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCenterValve1', ...
            'Timer', center_port.left_valve_time,...
            'StateChangeConditions', {'Tup', 'closeCenterValve1'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['O' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'closeCenterValve1', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitCenterSampleLick2'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['C' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'waitCenterSampleLick2', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LEFT_LICK_INPUT, 'openCenterValve2', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCenterValve2', ...
            'Timer', center_port.left_valve_time,...
            'StateChangeConditions', {'Tup', 'closeCenterValve2'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['O' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'closeCenterValve2', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitCenterSampleLick3'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['C' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'waitCenterSampleLick3', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LEFT_LICK_INPUT, 'openCenterValve3', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCenterValve3', ...
            'Timer', center_port.left_valve_time,...
            'StateChangeConditions', {'Tup', 'closeCenterValve3'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['O' center_port.left_valve]});
        sma = AddState(sma, 'Name', 'closeCenterValve3', ...
            'Timer', expV.STIMULUS_WINDOW,...
            'StateChangeConditions', {'Tup', 'TTC_LateralTimeout', expV.lickTimeExpired, 'TTC_LateralTimeout'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['C' center_port.left_valve]});
        
        %%%%% BEGIN TTC ON THE LATERAL PORTS %%%%%
        sma = AddState(sma, 'Name', 'TTC_LateralTimeout', ...
            'Timer', expV.DELAY_TIME,...
            'StateChangeConditions', {'Tup', 'TTC_Lateral'},...
            'OutputActions',{center_port.DOOR, expV.UP, 'GlobalCounterReset', port_3.COUNTER_ID});
        sma = AddState(sma, 'Name', 'TTC_Lateral', ...
            'Timer', expV.TTC_LATERAL_TIME,...
            'StateChangeConditions', {'Tup', 'reportSkip', correct_port.lick_input, 'waitLateralDryLicks', ...
            incorrect_port.lick_input, 'waitLateralDryLicks'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'GlobalCounterReset', port_1.COUNTER_ID});
        sma = AddState(sma, 'Name', 'waitLateralDryLicks', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.lick_counter_event, 'waitLateralRewardLick1', ...
            incorrect_port.lick_counter_event, 'waitFinalIncorrectLick', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'GlobalTimerTrig', expV.LICK_WINDOW_TIMER_ID});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick1', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.lick_input, 'openCorrectValve1', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve1', ...
            'Timer', correct_port.valve_time,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve1'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.valve]});
        sma = AddState(sma, 'Name', 'closeCorrectValve1', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitLateralRewardLick2'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.valve]});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick2', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.lick_input, 'openCorrectValve2', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve2', ...
            'Timer', correct_port.valve_time,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve2'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.valve]});
        sma = AddState(sma, 'Name', 'closeCorrectValve2', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitLateralRewardLick3'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.valve]});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick3', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.lick_input, 'openCorrectValve3', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve3', ...
            'Timer', correct_port.valve_time,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve3'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.valve]});
        sma = AddState(sma, 'Name', 'closeCorrectValve3', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitLateralRewardLick4'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.valve]});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick4', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.lick_input, 'openCorrectValve4', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve4', ...
            'Timer', correct_port.valve_time,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve4'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.valve], ...
            'SoftCode', 3});
        sma = AddState(sma, 'Name', 'closeCorrectValve4', ...
            'Timer', expV.STIMULUS_WINDOW,...
            'StateChangeConditions', {'Tup', 'ITI_end', expV.lickTimeExpired, 'ITI_end'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.valve]});
        % sma = AddState(sma, 'Name', 'waitRemainingLateralTime', ...
        %     'Timer', 0,...
        %     'StateChangeConditions', {expV.stimTimeExpired, 'ITI_end', expV.lickTimeExpired, 'ITI_end'},...
        %     'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'waitFinalIncorrectLick', ...
            'Timer', 0,...
            'StateChangeConditions', {incorrect_port.lick_input, 'reportIncorrect', expV.lickTimeExpired, 'reportSkip'},...
            'OutputActions',{port_1.DOOR, expV.DOWN, port_3.DOOR, expV.DOWN, 'SoftCode', 3});
        sma = AddState(sma, 'Name', 'reportIncorrect', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_punish'},...
            'OutputActions',{'SoftCode', 14});
        sma = AddState(sma, 'Name', 'reportSkip', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_punish'},...
            'OutputActions',{'SoftCode', 2});
        sma = AddState(sma, 'Name', 'ITI_end', ...
            'Timer', expV.ITI_ENDTIME,...
            'StateChangeConditions', {'Tup', 'resetCorrectCounter'},...
            'OutputActions',{port_1.DOOR, expV.UP, port_3.DOOR, expV.UP, 'SoftCode', 15});
        sma = AddState(sma, 'Name', 'ITI_punish', ...
            'Timer', (expV.PUNISHMENT_TIME + expV.ITI_ENDTIME),...
            'StateChangeConditions', {'Tup', 'resetCorrectCounter'},...
            'OutputActions',{port_1.DOOR, expV.UP, port_3.DOOR, expV.UP});
        
        %%%%% TRIAL END - reset counters %%%%%
        sma = AddState(sma, 'Name', 'resetCorrectCounter', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'resetIncorrectCounter'},...
            'OutputActions',{'GlobalCounterReset', correct_port.lick_counter_id});
        sma = AddState(sma, 'Name', 'resetIncorrectCounter', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'resetCenterCounter'},...
            'OutputActions',{'GlobalCounterReset', incorrect_port.lick_counter_id});
        sma = AddState(sma, 'Name', 'resetCenterCounter', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions',{'GlobalCounterReset', center_port.LEFT_COUNTER_ID});
        
        %%%%% SESSION END %%%%%
        sma = AddState(sma, 'Name', 'cleanup', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions',{port_1.DOOR, expV.UP, port_3.DOOR, expV.UP, 'ValveModule1', ['B' 00000000], 'BNC1', 0, 'SoftCode', 1});

        % function will check if softcode '1' has been sent by the state machine in cleanup state. 
        % if it has, it is time to exit the trial loop (end of session).

        BpodSystem.SoftCodeHandlerFunction = 'SoftCodeHandler';

        %% Send description to the Bpod State Machine device
        SendStateMachine(sma);

        % Run the trial
        events = RunStateMachine();
        if ~isempty(fieldnames(events)) % If you didn't stop the session manually mid-trial
            BpodSystem.Data = AddTrialEvents(BpodSystem.Data, events); % Adds raw events to a human-readable data struct
            SaveBpodSessionData; % Saves the field BpodSystem.Data to the current data file
        end
        HandlePauseCondition; % Checks to see if the protocol is paused. If so, waits until user resumes.

        fprintf('\n')

        % Check if experiment ends
        t = elapsedTime; 
        if (BpodSystem.Status.ExitTrialLoop || BpodSystem.Status.BeingUsed == 0 || trial == expV.MAXIMUM_TRIALS || t > expV.TOTAL_ALLOWED_TIME)
            disp(['Experiment duration: ' num2str(t) 'sec.' ])
            clear elapsedTime; 
            stop_experiment(A, W);
            sessionSummary();
            return
        end
    end
end
