% Original code written by Blake Hourigan for Samuelsen Lab, Univeristy of Louisville----
% V2 code and beyond edited/written by Timothy Vladimir Dong for Samuelsen Lab, Univeristy of Louisville----

%% TESTING PROTOCOL V3.6 | 2 OPERANT RESPONSE TASK
% This protocol is used with a center spout connected to a multi-channel manifold with a rinse and a gas line. 
% The inside of the spout only contains a single shared channel for all stimuli. Stimuli are loaded 
% from the manifold and rinsed out with gas and water. Rinse and waste stimuli are cleared by a waste vacuum 
% positioned in front of the spout. 
% 
% Lateral and center driver valves should be calibrated for 5ul pulses in ~70ms for delivering stimuli.  
% Stimulus and rinse valves should be calibrated for 100-600ul pulses in ~1000-3000ms for stimulus loading and rinse.  
% 
% V3.6 Update: all stimuli at the center port are delivered using a single "Driver" valve. Cleaning up code layout. 

function testing_v3
    
    global BpodSystem % Imports the BpodSystem object to the function workspace

    %% SESSION SETUP
    expV = ExperimentVariables(); %expV is used to access experiment constants

    BpodSystem.Status.trial = 1;
    BpodSystem.Status.ExitTrialLoop = false; % session end 
    BpodSystem.Status.switchStimulusFlag = false; % used to indicate when middle stimulus should switch (for alternation training only). 

    % Organizing what to save to data structure
    BpodSystem.Data.condition = ''; 
    BpodSystem.Data.trialOrder = []; 
    BpodSystem.Data.portInfo = [];
    BpodSystem.Data.summary.correctTrials = nan(expV.MAXIMUM_TRIALS, 1);
    BpodSystem.Data.summary.engagedTrials = nan(expV.MAXIMUM_TRIALS, 1);
    BpodSystem.Data.summary.correctPort = nan(expV.MAXIMUM_TRIALS, 1);
    
    % Generating trial order (determines each trial type)
    [trial_order, center_stim_valve_order] = GenerateTrialOrder();
    BpodSystem.Data.trialOrder.trialTypeOrder = trial_order; 
    BpodSystem.Data.trialOrder.centerValveOrder = center_stim_valve_order;
    
    % Saving ExperimentVariables
    propNames = properties(expV); propValues = cell(size(propNames));
    for i = 1:numel(propNames); propValues{i} = expV.(propNames{i}); end
    expVarTable = cell2table(propValues,'RowNames', propNames, 'VariableNames', {'Value'}); % Convert to table
    BpodSystem.Data.experimentVariables = expVarTable; % Save table to structure

    %% LOAD and UPDATE ProtocolSettings and Get Valve Timings
    S = BpodSystem.ProtocolSettings; % Loads settings file chosen in launch manager into current workspace as a struct called 'S'
    subject = BpodSystem.GUIData.SubjectName;
    if isempty(S) || isempty(fieldnames(S)) % If running this protocol for the first time with this subject, or if settings cannot be found
        dir = ['C:\Users\Chad Samuelsen\Documents\Github\Bpod Local\Data\',subject,'\Set_exp_parameters\Session Settings\DefaultSettings.mat'];
        temp = load(dir);
        S = temp.ProtocolSettings; clear temp;
        BpodSystem.ProtocolSettings = S;
    end
    
    % UPDATE valve open times
    deliveryValves = sort([expV.LEFT_VALVE, expV.CENTER_DRIVER_VALVE, expV.RIGHT_VALVE]); % Valves for delivering stimuli
    centerStimValves = [expV.CENTER_VALVE_SET1, expV.CENTER_VALVE_SET2]; % Valves for loading center port stimuli
    S = update_valve_open_times(S, deliveryValves, expV.STIM_VOLUME);
    
    % save delivery valve open times to session data
    valveID = strings(size(deliveryValves))'; 
    valveStimTimes = zeros(size(deliveryValves))';
    for iValve = 1:length(deliveryValves)
        valveID(iValve) = ['Valve', num2str(deliveryValves(iValve))];
        time_variable_name = sprintf('open_time_%d', deliveryValves(iValve));
        valveStimTimes(iValve) = round(BpodSystem.ProtocolSettings.GUI.(time_variable_name)/1000, 4);
    end
    BpodSystem.Data.valveTimings.valveStimTimes = table(valveID, valveStimTimes); % time in seconds
    
    % Get valve times for priming, loading, and rinse. 
    % Make sure the values allow for full ITI 
    valvePrimingTime = round(mean(GetValveTimes(expV.PRIMING_VOLUME, centerStimValves)),3); 
    valveLoadingTime = round(mean(GetValveTimes(expV.LOAD_VOLUME, centerStimValves)),3); 
    valveRinseTime = round(GetValveTimes(expV.RINSE_VOLUME, expV.RINSE_VALVE),3); 
    if (expV.ITI_TIME - expV.ITI_ENDTIME) < (valvePrimingTime + valveLoadingTime + (2*valveRinseTime) + (4*expV.GAS_TIME) + 1)
        error('Error: calibration values for rinse and preloading are incompatible with this protocol. '); 
    end

    % Save protocol settings (after updating valve timings)
    BpodSystem.ProtocolSettings = S;
    SaveProtocolSettings(BpodSystem.ProtocolSettings)
    
    BpodParameterGUI('init', S); % initialize GUI to keep track of parameters

    % GET CONDITION FOR CURRENT SUBJECT
    condition = S.GUIMeta.CONDITION_CODE.String;
    if ~any(contains(condition, "null")); error('Error: no condition selected for this subject. '); end
    SUBJECT_CONDITION_CODE = condition(~contains(condition, "null")); 
    BpodSystem.Data.condition = SUBJECT_CONDITION_CODE;
    
    %% Generate port instances
    % port 1 = LEFT, port 2 = CENTER, port 3 = RIGHT
    
    % Instances of each port class are constant throughout the session. 
    left_port = Port(1, expV.LEFT_VALVE, valveStimTimes(deliveryValves == expV.LEFT_VALVE)); 
    center_port = Port(2, expV.CENTER_DRIVER_VALVE, valveStimTimes(deliveryValves == expV.CENTER_DRIVER_VALVE)); 
    right_port = Port(3, expV.RIGHT_VALVE, valveStimTimes(deliveryValves == expV.RIGHT_VALVE)); 
    
    % Instances of the PortMaster class receive the properties of the left or right ports according to the trial. 
    % This determines which port is correct or incorrect for each trial. 
    correct_port = PortTrialManager; 
    incorrect_port = PortTrialManager; 

    % save port properties
    BpodSystem.Data.portInfo.port1 = left_port; 
    BpodSystem.Data.portInfo.port2 = center_port; 
    BpodSystem.Data.portInfo.port3 = right_port; 
    
    %% Configure analog in and waveplayer modules
    ValveModule = ConfigureValveModule(); % configure valve module to manage valves
    AnalogInModule = ConfigureAnalogIn(); % configure the analog in module to record and generate events
    WavePlayerModule = ConfigureWavePlayer(); % configure waveplayer module (analog out) to generate tones

    %% Print to command window the start of the Session
    disp(['Subject Name: ' subject]);
    disp(['Condition: ' char(SUBJECT_CONDITION_CODE)]);
    fprintf('Date and time: %s\n', datetime("now"));
    disp(['Water valves: [', num2str(expV.CENTER_VALVE_SET1), ']. Odor valves: [', num2str(expV.CENTER_VALVE_SET2), '].']); 
    fprintf(['Valve Durations (' num2str(expV.STIM_VOLUME), 'ul): ']); 
    for iValves=1:length(valveID); fprintf('%s=%.1fms. ', valveID(iValves), valveStimTimes(iValves)*1000); end
    fprintf(['\nPriming: ' num2str(expV.PRIMING_VOLUME), 'ul, ', num2str(valvePrimingTime), 's. ']);
    fprintf(['Load: ' num2str(expV.LOAD_VOLUME), 'ul, ', num2str(valveLoadingTime), 's. ']);
    fprintf(['Rinse: ' num2str(expV.RINSE_VOLUME), 'ul, ', num2str(valveRinseTime), 's per pulse (x2 pulses). \n']);
    
    clear elapsedTime; 
    elapsedTime; % First call of timer function to track session length

    %% MAIN TRIAL LOOP
    % do MAXIMUM_TRIALS as defined in ExperimentVariables file if 60 minutes has not elapsed.
    for trial = 1:expV.MAXIMUM_TRIALS
        
        S = BpodParameterGUI('sync', S); % Sync parameters with BpodParameterGUI plugin
        
        %% Get parameters for the current trial and save to variables
        BpodSystem.Status.trial  = trial;
        fprintf('Trial %d: ', trial)
        if trial_order(trial) == 0; fprintf('Water trial. '); else; fprintf('Odor trial.  '); end

        center_stimulus_valve = center_stim_valve_order(trial); % Get center valve and number of dry licks for this trial

        % Set center valve and correct port -> WHERE CORRECT CHOICE IS DEFINED
        correct_port = correct_port.setCorrect(left_port, right_port, center_stimulus_valve, ...
            expV.CENTER_VALVE_SET1, expV.CENTER_VALVE_SET2, SUBJECT_CONDITION_CODE);
        incorrect_port = incorrect_port.setIncorrect(left_port, right_port, center_stimulus_valve, ...
            expV.CENTER_VALVE_SET1, expV.CENTER_VALVE_SET2, SUBJECT_CONDITION_CODE);

        BpodSystem.Data.summary.correctPort(trial) = correct_port.PORT;
        fprintf(['Center=valve', num2str(center_stimulus_valve), '. Correct=port', num2str(correct_port.PORT),'. ']);

        %% Assemble the State Machine for this Trial
        sma = NewStateMachine();

        % set global timers for the maximum duration of the experiment and the maximum sample time of 2 seconds.
        sma = SetGlobalTimer(sma, 'TimerID', expV.ITI_TIMER_ID, 'Duration', (expV.ITI_TIME - expV.ITI_ENDTIME) );
        sma = SetGlobalTimer(sma, 'TimerID', expV.LICK_WINDOW_TIMER_ID, 'Duration', expV.LICK_WINDOW); % 2 seconds to get all licks

        % set global counters for each of the possible input ports (AnalogIn1 ports 1-3). 
        sma = SetGlobalCounter(sma, left_port.COUNTER_ID, left_port.LICK_ONSET, 3);
        sma = SetGlobalCounter(sma, center_port.COUNTER_ID, center_port.LICK_ONSET, 3); 
        sma = SetGlobalCounter(sma, right_port.COUNTER_ID, right_port.LICK_ONSET, 3);

        %% Adding States

        %%%% MAIN ITI WITH GAS CLEARING, WATER RINSE, AND STIMULUS LOADING %%%%%
        sma = AddState(sma, 'Name', 'trialStart', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_gasClear1'},...
            'OutputActions', {left_port.DOOR, expV.UP, center_port.DOOR, expV.UP, right_port.DOOR, expV.UP, ...
            'ValveModule1', ['B' 0], expV.GAS_VALVE, 0});
        sma = AddState(sma, 'Name', 'ITI_gasClear1', ...
            'Timer', expV.GAS_TIME,...
            'StateChangeConditions', {'Tup', 'ITI_gasDelay1'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 1,'GlobalTimerTrig', expV.ITI_TIMER_ID});
        sma = AddState(sma, 'Name', 'ITI_gasDelay1', ...
            'Timer', expV.GAS_DELAY,...
            'StateChangeConditions', {'Tup', 'ITI_rinse1'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0});
        sma = AddState(sma, 'Name', 'ITI_rinse1', ...
            'Timer', valveRinseTime,...
            'StateChangeConditions', {'Tup', 'ITI_gasClear2'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0, 'ValveModule1', ['O' expV.RINSE_VALVE]});
        sma = AddState(sma, 'Name', 'ITI_gasClear2', ...
            'Timer', expV.GAS_TIME,...
            'StateChangeConditions', {'Tup', 'ITI_gasDelay2'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 1, 'ValveModule1', ['C' expV.RINSE_VALVE]});  
        sma = AddState(sma, 'Name', 'ITI_gasDelay2', ...
            'Timer', expV.GAS_DELAY,...
            'StateChangeConditions', {'Tup', 'ITI_rinse2'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0});
        sma = AddState(sma, 'Name', 'ITI_rinse2', ...
            'Timer', valveRinseTime,...
            'StateChangeConditions', {'Tup', 'ITI_gasClear3'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0, 'ValveModule1', ['O' expV.RINSE_VALVE]});
        sma = AddState(sma, 'Name', 'ITI_gasClear3', ...
            'Timer', expV.GAS_TIME,...
            'StateChangeConditions', {'Tup', 'ITI_gasDelay3'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 1, 'ValveModule1', ['C' expV.RINSE_VALVE]}); 
        sma = AddState(sma, 'Name', 'ITI_gasDelay3', ...
            'Timer', expV.GAS_DELAY,...
            'StateChangeConditions', {'Tup', 'ITI_stimPriming'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0});
        sma = AddState(sma, 'Name', 'ITI_stimPriming', ...
            'Timer', valvePrimingTime,...
            'StateChangeConditions', {'Tup', 'ITI_stimPrimingDelay'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0, 'ValveModule1', ['O' center_stimulus_valve]});
         sma = AddState(sma, 'Name', 'ITI_stimPrimingDelay', ...
            'Timer', expV.PRIMING_DELAY,...
            'StateChangeConditions', {'Tup', 'ITI_gasClear4'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0, 'ValveModule1', ['C' center_stimulus_valve]});
        sma = AddState(sma, 'Name', 'ITI_gasClear4', ...
            'Timer', expV.GAS_TIME,...
            'StateChangeConditions', {'Tup', 'ITI_gasDelay4'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 1}); 
        sma = AddState(sma, 'Name', 'ITI_gasDelay4', ...
            'Timer', expV.GAS_DELAY,...
            'StateChangeConditions', {'Tup', 'ITI_stimLoad'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0});
        sma = AddState(sma, 'Name', 'ITI_stimLoad', ...
            'Timer', valveLoadingTime,...
            'StateChangeConditions', {'Tup', 'ITI_waitForRemaining'},...
            'OutputActions',{center_port.DOOR, expV.UP, expV.GAS_VALVE, 0, 'ValveModule1', ['O' center_stimulus_valve]});
        sma = AddState(sma, 'Name', 'ITI_waitForRemaining', ...
            'Timer', 0,...
            'StateChangeConditions', {expV.ITI_TIMER_END, 'TTC_Center'},...
            'OutputActions',{center_port.DOOR, expV.UP, 'ValveModule1', ['C' center_stimulus_valve], ...
            'GlobalCounterReset', center_port.COUNTER_ID});
        
        %%%%% TRIAL START %%%%%
        sma = AddState(sma, 'Name', 'TTC_Center', ...
            'Timer', expV.TTC_CENTER_TIME,...
            'StateChangeConditions', {'Tup', 'reportSkip', center_port.LICK_ONSET, 'waitCenterDryLicks'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'AnalogIn1', ['#' 0], 'WavePlayer1', ['P' 8 0]});
        sma = AddState(sma, 'Name', 'waitCenterDryLicks', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.COUNTER_EVENT, 'waitCenterSampleLick1', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'GlobalTimerTrig', expV.LICK_WINDOW_TIMER_ID});
        sma = AddState(sma, 'Name', 'waitCenterSampleLick1', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LICK_OFFSET, 'openCenterValve1', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCenterValve1', ...
            'Timer', center_port.VALVE_TIME,...
            'StateChangeConditions', {'Tup', 'closeCenterValve1'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['O' center_port.VALVE]});
        sma = AddState(sma, 'Name', 'closeCenterValve1', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitCenterSampleLick2'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['C' center_port.VALVE]});
        sma = AddState(sma, 'Name', 'waitCenterSampleLick2', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LICK_OFFSET, 'openCenterValve2', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCenterValve2', ...
            'Timer', center_port.VALVE_TIME,...
            'StateChangeConditions', {'Tup', 'closeCenterValve2'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['O' center_port.VALVE]});
        sma = AddState(sma, 'Name', 'closeCenterValve2', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitCenterSampleLick3'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['C' center_port.VALVE]});
        sma = AddState(sma, 'Name', 'waitCenterSampleLick3', ...
            'Timer', 0,...
            'StateChangeConditions', {center_port.LICK_OFFSET, 'openCenterValve3', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{center_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCenterValve3', ...
            'Timer', center_port.VALVE_TIME,...
            'StateChangeConditions', {'Tup', 'closeCenterValve3'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['O' center_port.VALVE]});
        sma = AddState(sma, 'Name', 'closeCenterValve3', ...
            'Timer', expV.STIMULUS_WINDOW,...
            'StateChangeConditions', {'Tup', 'TTC_LateralTimeout', expV.LICK_WINDOW_TIMER_END, 'TTC_LateralTimeout'},...
            'OutputActions',{center_port.DOOR, expV.DOWN, 'ValveModule1', ['C' center_port.VALVE]});
        
        %%%%% BEGIN TTC ON THE LATERAL PORTS %%%%%
        sma = AddState(sma, 'Name', 'TTC_LateralTimeout', ...
            'Timer', expV.DELAY_TIME,...
            'StateChangeConditions', {'Tup', 'TTC_Lateral'},...
            'OutputActions',{center_port.DOOR, expV.UP, 'GlobalCounterReset', incorrect_port.COUNTER_ID});
        sma = AddState(sma, 'Name', 'TTC_Lateral', ...
            'Timer', expV.TTC_LATERAL_TIME,...
            'StateChangeConditions', {'Tup', 'reportSkip', correct_port.LICK_ONSET, 'waitLateralDryLicks', ...
            incorrect_port.LICK_ONSET, 'waitLateralDryLicks'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'GlobalCounterReset', correct_port.COUNTER_ID});
        sma = AddState(sma, 'Name', 'waitLateralDryLicks', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.COUNTER_EVENT, 'waitLateralRewardLick1', ...
            incorrect_port.COUNTER_EVENT, 'waitFinalIncorrectLick', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'GlobalTimerTrig', expV.LICK_WINDOW_TIMER_ID});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick1', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.LICK_OFFSET, 'openCorrectValve1', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve1', ...
            'Timer', correct_port.VALVE_TIME,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve1'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.VALVE]});
        sma = AddState(sma, 'Name', 'closeCorrectValve1', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitLateralRewardLick2'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.VALVE]});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick2', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.LICK_OFFSET, 'openCorrectValve2', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve2', ...
            'Timer', correct_port.VALVE_TIME,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve2'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.VALVE]});
        sma = AddState(sma, 'Name', 'closeCorrectValve2', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'waitLateralRewardLick3'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.VALVE]});
        sma = AddState(sma, 'Name', 'waitLateralRewardLick3', ...
            'Timer', 0,...
            'StateChangeConditions', {correct_port.LICK_OFFSET, 'openCorrectValve3', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'openCorrectValve3', ...
            'Timer', correct_port.VALVE_TIME,...
            'StateChangeConditions', {'Tup', 'closeCorrectValve3'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'ValveModule1', ['O', correct_port.VALVE]});
        sma = AddState(sma, 'Name', 'closeCorrectValve3', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_correctTrialEnd', expV.LICK_WINDOW_TIMER_END, 'ITI_correctTrialEnd'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN, 'ValveModule1', ['C', correct_port.VALVE]});
        sma = AddState(sma, 'Name', 'waitFinalIncorrectLick', ...
            'Timer', 0,...
            'StateChangeConditions', {incorrect_port.LICK_ONSET, 'reportIncorrect', expV.LICK_WINDOW_TIMER_END, 'reportSkip'},...
            'OutputActions',{left_port.DOOR, expV.DOWN, right_port.DOOR, expV.DOWN});
        sma = AddState(sma, 'Name', 'reportIncorrect', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_punishTrialEnd'},...
            'OutputActions',{'SoftCode', 14});
        sma = AddState(sma, 'Name', 'reportSkip', ...
            'Timer', 0,...
            'StateChangeConditions', {'Tup', 'ITI_punishTrialEnd'},...
            'OutputActions',{'SoftCode', 2});
        sma = AddState(sma, 'Name', 'ITI_correctTrialEnd', ...
            'Timer', expV.ITI_ENDTIME,...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions',{left_port.DOOR, expV.UP, right_port.DOOR, expV.UP, 'SoftCode', 15});
        sma = AddState(sma, 'Name', 'ITI_punishTrialEnd', ...
            'Timer', expV.ITI_ENDTIME,...
            'StateChangeConditions', {'Tup', 'ITI_punishExtraGasClear'},...
            'OutputActions',{left_port.DOOR, expV.UP, right_port.DOOR, expV.UP});
        sma = AddState(sma, 'Name', 'ITI_punishExtraGasClear', ...
            'Timer', expV.GAS_TIME_PUNISH,...
            'StateChangeConditions', {'Tup', 'ITI_punish'},...
            'OutputActions',{left_port.DOOR, expV.UP, right_port.DOOR, expV.UP, expV.GAS_VALVE, 1});
        sma = AddState(sma, 'Name', 'ITI_punish', ...
            'Timer', (expV.PUNISHMENT_TIME - expV.GAS_TIME_PUNISH),...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions',{left_port.DOOR, expV.UP, right_port.DOOR, expV.UP, 'ValveModule1', ['B' 0], expV.GAS_VALVE, 0});
        
        %%%%% TRIAL END %%%%%

        BpodSystem.SoftCodeHandlerFunction = 'SoftCodeHandler';

        %% Send description to the Bpod State Machine device
        SendStateMachine(sma);

        % Run the trial
        events = RunStateMachine();
        if ~isempty(fieldnames(events)) % If you didn't stop the session manually mid-trial
            BpodSystem.Data = AddTrialEvents(BpodSystem.Data, events); % Adds raw events to a human-readable data struct
            SaveBpodSessionData; % Saves the field BpodSystem.Data to the current data file
        end
        HandlePauseCondition; % Checks to see if the protocol is paused. If so, waits until user resumes.

        fprintf('\n')

        % Check if experiment ends
        t = elapsedTime; 
        if (BpodSystem.Status.ExitTrialLoop || BpodSystem.Status.BeingUsed == 0 || trial == expV.MAXIMUM_TRIALS || t > expV.TOTAL_ALLOWED_TIME)
            disp(['Experiment duration: ' num2str(t) 'sec.' ])
            clear elapsedTime;
            
            AnalogInModule.scope_StartStop;
            AnalogInModule.endAcq; % Close Oscope GUI
            AnalogInModule.stopReportingEvents; % Stop sending events to state machine
            ValveModule.isOpen = zeros(1,8); % close all valves
            clear AnalogInModule
            clear WavePlayerModule
            clear ValveModule
            
            sessionSummary();
            return
        end
    end
end

function V = ConfigureValveModule
    global BpodSystem
    
    BpodSystem.assertModule('ValveModule');
    
    V = ValveDriverModule(BpodSystem.ModuleUSB.ValveModule1);
end

function A = ConfigureAnalogIn
    global BpodSystem

    BpodSystem.assertModule('AnalogIn', 1); % Assert Analog Input module is present + USB-paired (via USB button on console GUI)

    A = BpodAnalogIn(BpodSystem.ModuleUSB.AnalogIn1);
    
    A.SamplingRate = 5000; % Set the sampling rate to 5kHz
    A.nActiveChannels = 3;
    % enable event reporting on AnalogInput1. This sends lick 'events' to the state machine to be processed/counted.
    [A.InputRange{1:3}] = deal('0V:5V'); % Set input range
    A.SMeventsEnabled(1:3) = 1; 
    % This sets threshold voltages that we want to cross to generate events. 
    % Here we have 2 thresholds per channel, the first one for lick onset (5v) and the second for lick offset (1v)
    A.Thresholds = [5 5 5 5 0 0 0 0; 1 1 1 1 0 0 0 0];
    % ResetVoltages sets the voltage bound that must be crossed before a new event can be generated
    A.ResetVoltages = [1 1 1 1 0 0 0 0; 5 5 5 5 0 0 0 0];
    % Tell the AnalogInput1 module to start reporting events to the
    % state machine
    A.startReportingEvents();
    % View all channels by default - added by TVD 10/11/2025
    A.Stream2USB(1:3) = 1;
    
    %behaviorDataFile = BpodSystem.Path.CurrentDataFile;
    %A.USBStreamFile = [behaviorDataFile(1:end-4) '_Alg.mat']; % Set datafile for analog data captured in this session
    
    % start the oscilliscope.
    A.scope();
    A.scope_StartStop;
end

function W = ConfigureWavePlayer
    global BpodSystem
    
    % Variables for wave player
    Fs = 44100;    % Sampling rate in Hz (e.g., CD quality)
    T = .5;         % Duration in seconds
    f = 800;       % Frequency of the tone in Hz
    t = 0:1/Fs:T; % Generate the time vector
    y = sin(2*pi*f*t); % Generate the sinusoidal waveform
    
    BpodSystem.assertModule('WavePlayer', 1);
    
    W = BpodWavePlayer(BpodSystem.ModuleUSB.WavePlayer1);
    W.SamplingRate = Fs;
    W.loadWaveform(1, y); % Loads a sound as waveform 1
end